languageCode = "ru"
languageName = "Русский"

[params]
  displayName = "Русский"
  isoCode = "ru"
  rtl = false
  dateFormat = "2 January 2006"

[params.author]
name = "Никита Савченко (NikitaSavc)"
image = "img/author.jpg"
headline = "Web / Android / JavaScript / C++ разработчик"
bio = "15"
links = [
  { github = "https://github.com/NikitaSavc" },
  { telegram = "https://t.me/NikitaSavc" },
  { email = "NikitaSavc@yandex.ru" }
]
